Feature/opt out message
greatnonprofits-nfp/courier pull request #29
Opened 2022-02-02 19:38 UTC by teehamaral

https://app.asana.com/0/1201638023907740/1201674230141709

2022-02-03 09:49 UTC, musamusa approved these changes

2022-02-03 11:12 UTC, ihor-palii requested changes

2022-02-03 11:12 UTC, ihor-palii commented on backends/rapidpro/backend.go
> +func (b *backend) NewMsgOutgoing(channel courier.Channel, urn urns.URN, text string) courier.Msg {
We already have the `NewOutgoingMsg` method with the same logic. So I guess this method can be removed.

2022-02-03 11:12 UTC, ihor-palii commented on backend.go
> +	NewMsgOutgoing(channel Channel, urn urns.URN, text string) Msg
Need to be replaced with `NewOutgoingMsg` that was already implemented.

2022-02-03 11:12 UTC, ihor-palii commented on handlers/twiml/twiml.go
> +		msgBack := h.Backend().NewMsgOutgoing(channel, urn, textMessage.(string))
Replace `NewMsgOutgoing` with `NewOutgoingMsg`.

2022-02-03 11:12 UTC, ihor-palii commented on test.go
> +func (mb *MockBackend) NewMsgOutgoing(channel Channel, urn urns.URN, text string) Msg {
Can de removed as ve have `NewOutgoingMsg`

2022-02-08 13:17 UTC, ihor-palii approved these changes

2022-02-08 14:44 UTC, merged